global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.

scrape_configs:
  - job_name: "koa"
    static_configs:
      - targets: ["host.docker.internal:3333"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['host.docker.internal:9093']

rule_files:
  - "/etc/prometheus/rules/*.yml"
