version: "2"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    extra_hosts:
      - host.docker.internal:host-gateway # allow access to host
    ports:
      - "3000:3000"

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - 9091:9091

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules/rules.yml
      - ./prometheus_data:/prometheus_data:rw
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - '--storage.tsdb.path=/prometheus_data'
      - "--storage.tsdb.retention.time=10d"  # When to remove old data. Defaults to 15d
      - "--storage.tsdb.retention.size=200MB" # The maximum number of bytes of storage blocks to retain. The oldest data will be removed first. Defaults disabled.
    extra_hosts:
      - host.docker.internal:host-gateway # allow access to host
    ports:
      - "9090:9090" # Bind port 9090 of the container to port 9090 of the host





