groups:
  - name: ops # 告警规则组的名称
    rules:
    - alert: no pv # 告警规则的名称
      expr: sum (increase(request_count[1m])) < 1 # 告警条件
      for: 5m # 持续满足告警条件时长。 default = 0s
      labels:
        serverity: high
        team: ls
      annotations:
        summary: "no pv over 1 minute"

